
server:
  port: 8079
spring:
  application:
    # 微服务名称
    name: depart-provider
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: CY20030916
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        # nacos注册中心地址
        server-addr: localhost:8848
        username: nacos
        password: nacos

# 配置日志
logging:
  # 控制台日志的输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info
