
spring:
    application:
        # 微服务名称
        name: depart-consumer

    cloud:
        nacos:
            discovery:
                # nacos注册中心地址
                server-addr: localhost:8848
                username: nacos
                password: nacos